# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: agent_platform/service/v1/agent_service.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

import agent_platform.service.v1.agent_service_pb2 as agent__platform_dot_service_dot_v1_dot_agent__service__pb2


class AgentService(Protocol):
    async def create_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def run_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def stream_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
        ctx: RequestContext,
    ) -> AsyncIterator[
        agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse
    ]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_agent_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgentServiceASGIApplication(ConnectASGIApplication):
    def __init__(
        self,
        service: AgentService,
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_platform.service.v1.AgentService/CreateAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_agent,
                ),
                "/agent_platform.service.v1.AgentService/GetAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent,
                ),
                "/agent_platform.service.v1.AgentService/ListAgents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAgents",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agents,
                ),
                "/agent_platform.service.v1.AgentService/UpdateAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_agent,
                ),
                "/agent_platform.service.v1.AgentService/DeleteAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_agent,
                ),
                "/agent_platform.service.v1.AgentService/RunAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="RunAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_agent,
                ),
                "/agent_platform.service.v1.AgentService/StreamAgentRun": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StreamAgentRun",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stream_agent_run,
                ),
                "/agent_platform.service.v1.AgentService/GetAgentRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAgentRun",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent_run,
                ),
                "/agent_platform.service.v1.AgentService/ListAgentRuns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAgentRuns",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agent_runs,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_platform.service.v1.AgentService"


class AgentServiceClient(ConnectClient):
    async def create_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgents",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def run_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[
        agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse
    ]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamAgentRun",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentRun",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_agent_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentRuns",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AgentServiceSync(Protocol):
    def create_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def update_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def delete_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def run_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def stream_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
        ctx: RequestContext,
    ) -> Iterator[
        agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse
    ]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_agent_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AgentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AgentServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_platform.service.v1.AgentService/CreateAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_agent,
                ),
                "/agent_platform.service.v1.AgentService/GetAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent,
                ),
                "/agent_platform.service.v1.AgentService/ListAgents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAgents",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agents,
                ),
                "/agent_platform.service.v1.AgentService/UpdateAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_agent,
                ),
                "/agent_platform.service.v1.AgentService/DeleteAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_agent,
                ),
                "/agent_platform.service.v1.AgentService/RunAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="RunAgent",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_agent,
                ),
                "/agent_platform.service.v1.AgentService/StreamAgentRun": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StreamAgentRun",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stream_agent_run,
                ),
                "/agent_platform.service.v1.AgentService/GetAgentRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAgentRun",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_agent_run,
                ),
                "/agent_platform.service.v1.AgentService/ListAgentRuns": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAgentRuns",
                        service_name="agent_platform.service.v1.AgentService",
                        input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_agent_runs,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_platform.service.v1.AgentService"


class AgentServiceClientSync(ConnectClientSync):
    def create_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.CreateAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgents",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.UpdateAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.DeleteAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def run_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunAgent",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.RunAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[
        agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse
    ]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamAgentRun",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.StreamAgentRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_agent_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAgentRun",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.GetAgentRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_agent_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAgentRuns",
                service_name="agent_platform.service.v1.AgentService",
                input=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsRequest,
                output=agent__platform_dot_service_dot_v1_dot_agent__service__pb2.ListAgentRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
