# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: agent_platform/service/v1/policy_service.proto

from collections.abc import Iterable, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

import agent_platform.service.v1.policy_service_pb2 as agent__platform_dot_service_dot_v1_dot_policy__service__pb2


class PolicyService(Protocol):
    async def create_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_policy_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def run_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_policy_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_policy_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PolicyServiceASGIApplication(ConnectASGIApplication):
    def __init__(
        self,
        service: PolicyService,
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_platform.service.v1.PolicyService/CreatePolicyAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/GetPolicyAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/ListPolicyAgents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPolicyAgents",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_policy_agents,
                ),
                "/agent_platform.service.v1.PolicyService/UpdatePolicyAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdatePolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/DeletePolicyAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeletePolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/RunPolicyAgent": Endpoint.unary(
                    method=MethodInfo(
                        name="RunPolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/GetPolicyRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPolicyRun",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_policy_run,
                ),
                "/agent_platform.service.v1.PolicyService/ListPolicyRuns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPolicyRuns",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_policy_runs,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_platform.service.v1.PolicyService"


class PolicyServiceClient(ConnectClient):
    async def create_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_policy_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPolicyAgents",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def run_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunPolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_policy_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPolicyRun",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_policy_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPolicyRuns",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class PolicyServiceSync(Protocol):
    def create_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_policy_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def update_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def delete_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def run_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_policy_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_policy_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PolicyServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: PolicyServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_platform.service.v1.PolicyService/CreatePolicyAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/GetPolicyAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/ListPolicyAgents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPolicyAgents",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_policy_agents,
                ),
                "/agent_platform.service.v1.PolicyService/UpdatePolicyAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdatePolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/DeletePolicyAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeletePolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/RunPolicyAgent": EndpointSync.unary(
                    method=MethodInfo(
                        name="RunPolicyAgent",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_policy_agent,
                ),
                "/agent_platform.service.v1.PolicyService/GetPolicyRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPolicyRun",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_policy_run,
                ),
                "/agent_platform.service.v1.PolicyService/ListPolicyRuns": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPolicyRuns",
                        service_name="agent_platform.service.v1.PolicyService",
                        input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_policy_runs,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_platform.service.v1.PolicyService"


class PolicyServiceClientSync(ConnectClientSync):
    def create_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.CreatePolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_policy_agents(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPolicyAgents",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyAgentsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.UpdatePolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.DeletePolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def run_policy_agent(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunPolicyAgent",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.RunPolicyAgentResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_policy_run(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPolicyRun",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.GetPolicyRunResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_policy_runs(
        self,
        request: agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPolicyRuns",
                service_name="agent_platform.service.v1.PolicyService",
                input=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsRequest,
                output=agent__platform_dot_service_dot_v1_dot_policy__service__pb2.ListPolicyRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
