# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: agent_platform/service/v1/tool_service.proto

from collections.abc import Iterable, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

import agent_platform.service.v1.tool_service_pb2 as agent__platform_dot_service_dot_v1_dot_tool__service__pb2


class ToolService(Protocol):
    async def create_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_tools(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ToolServiceASGIApplication(ConnectASGIApplication):
    def __init__(
        self,
        service: ToolService,
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_platform.service.v1.ToolService/CreateTool": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_tool,
                ),
                "/agent_platform.service.v1.ToolService/GetTool": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_tool,
                ),
                "/agent_platform.service.v1.ToolService/ListTools": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTools",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_tools,
                ),
                "/agent_platform.service.v1.ToolService/UpdateTool": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_tool,
                ),
                "/agent_platform.service.v1.ToolService/DeleteTool": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_tool,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_platform.service.v1.ToolService"


class ToolServiceClient(ConnectClient):
    async def create_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_tools(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTools",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ToolServiceSync(Protocol):
    def create_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_tools(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def update_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def delete_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
        ctx: RequestContext,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ToolServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ToolServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/agent_platform.service.v1.ToolService/CreateTool": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_tool,
                ),
                "/agent_platform.service.v1.ToolService/GetTool": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_tool,
                ),
                "/agent_platform.service.v1.ToolService/ListTools": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTools",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_tools,
                ),
                "/agent_platform.service.v1.ToolService/UpdateTool": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_tool,
                ),
                "/agent_platform.service.v1.ToolService/DeleteTool": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteTool",
                        service_name="agent_platform.service.v1.ToolService",
                        input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
                        output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_tool,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/agent_platform.service.v1.ToolService"


class ToolServiceClientSync(ConnectClientSync):
    def create_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.CreateToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.GetToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_tools(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTools",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.ListToolsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.UpdateToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_tool(
        self,
        request: agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTool",
                service_name="agent_platform.service.v1.ToolService",
                input=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolRequest,
                output=agent__platform_dot_service_dot_v1_dot_tool__service__pb2.DeleteToolResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
