# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_platform/common/v1/types.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "agent_platform/common/v1/types.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$agent_platform/common/v1/types.proto\x12\x18\x61gent_platform.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\x90\x01\n\x08Metadata\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x39\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAt"H\n\nPagination\x12\x1b\n\tpage_size\x18\x01 \x01(\x05R\x08pageSize\x12\x1d\n\npage_token\x18\x02 \x01(\tR\tpageToken"]\n\x12PaginationResponse\x12&\n\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1f\n\x0btotal_count\x18\x02 \x01(\x05R\ntotalCount*r\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15STATUS_AWAITING_START\x10\x01\x12\x12\n\x0eSTATUS_RUNNING\x10\x02\x12\x0f\n\x0bSTATUS_DONE\x10\x03\x12\x10\n\x0cSTATUS_ERROR\x10\x04\x42\xeb\x01\n\x1c\x63om.agent_platform.common.v1B\nTypesProtoP\x01ZAgithub.com/agentplatform/gen/go/agent_platform/common/v1;commonv1\xa2\x02\x03\x41\x43X\xaa\x02\x17\x41gentPlatform.Common.V1\xca\x02\x17\x41gentPlatform\\Common\\V1\xe2\x02#AgentPlatform\\Common\\V1\\GPBMetadata\xea\x02\x19\x41gentPlatform::Common::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_platform.common.v1.types_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\034com.agent_platform.common.v1B\nTypesProtoP\001ZAgithub.com/agentplatform/gen/go/agent_platform/common/v1;commonv1\242\002\003ACX\252\002\027AgentPlatform.Common.V1\312\002\027AgentPlatform\\Common\\V1\342\002#AgentPlatform\\Common\\V1\\GPBMetadata\352\002\031AgentPlatform::Common::V1"
    _globals["_STATUS"]._serialized_start = 415
    _globals["_STATUS"]._serialized_end = 529
    _globals["_METADATA"]._serialized_start = 100
    _globals["_METADATA"]._serialized_end = 244
    _globals["_PAGINATION"]._serialized_start = 246
    _globals["_PAGINATION"]._serialized_end = 318
    _globals["_PAGINATIONRESPONSE"]._serialized_start = 320
    _globals["_PAGINATIONRESPONSE"]._serialized_end = 413
# @@protoc_insertion_point(module_scope)
