# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_platform/agent/v1/agent.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "agent_platform/agent/v1/agent.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#agent_platform/agent/v1/agent.proto\x12\x17\x61gent_platform.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\xdd\x02\n\x05\x41gent\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n\x04task\x18\x03 \x01(\tR\x04task\x12\x19\n\x08tool_ids\x18\x04 \x03(\tR\x07toolIds\x12#\n\rsystem_prompt\x18\x05 \x01(\tR\x0csystemPrompt\x12(\n\x10policy_agent_ids\x18\x06 \x03(\tR\x0epolicyAgentIds\x12<\n\x06\x63onfig\x18\x07 \x01(\x0b\x32$.agent_platform.agent.v1.AgentConfigR\x06\x63onfig\x12\x39\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAt"\x8a\x01\n\x0b\x41gentConfig\x12\x14\n\x05model\x18\x01 \x01(\tR\x05model\x12 \n\x0btemperature\x18\x02 \x01(\x02R\x0btemperature\x12\x1d\n\nmax_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12$\n\x0emax_tool_calls\x18\x04 \x01(\x05R\x0cmaxToolCallsB\xe4\x01\n\x1b\x63om.agent_platform.agent.v1B\nAgentProtoP\x01Z?github.com/agentplatform/gen/go/agent_platform/agent/v1;agentv1\xa2\x02\x03\x41\x41X\xaa\x02\x16\x41gentPlatform.Agent.V1\xca\x02\x16\x41gentPlatform\\Agent\\V1\xe2\x02"AgentPlatform\\Agent\\V1\\GPBMetadata\xea\x02\x18\x41gentPlatform::Agent::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_platform.agent.v1.agent_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b'\n\033com.agent_platform.agent.v1B\nAgentProtoP\001Z?github.com/agentplatform/gen/go/agent_platform/agent/v1;agentv1\242\002\003AAX\252\002\026AgentPlatform.Agent.V1\312\002\026AgentPlatform\\Agent\\V1\342\002"AgentPlatform\\Agent\\V1\\GPBMetadata\352\002\030AgentPlatform::Agent::V1'
    _globals["_AGENT"]._serialized_start = 98
    _globals["_AGENT"]._serialized_end = 447
    _globals["_AGENTCONFIG"]._serialized_start = 450
    _globals["_AGENTCONFIG"]._serialized_end = 588
# @@protoc_insertion_point(module_scope)
