# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_platform/agent/v1/agent_run.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "agent_platform/agent/v1/agent_run.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\'agent_platform/agent/v1/agent_run.proto\x12\x17\x61gent_platform.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a$agent_platform/common/v1/types.proto\x1a#agent_platform/agent/v1/block.proto\x1a&agent_platform/tool/v1/tool_call.proto"\xbe\x04\n\x08\x41gentRun\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n\x08\x61gent_id\x18\x02 \x01(\tR\x07\x61gentId\x12\x39\n\nstarted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n\x0b\x66inished_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\nfinishedAt\x12\x36\n\x06\x62locks\x18\x05 \x03(\x0b\x32\x1e.agent_platform.agent.v1.BlockR\x06\x62locks\x12\x62\n\x15\x66orce_final_tool_call\x18\x06 \x01(\x0b\x32*.agent_platform.tool.v1.ForceFinalToolCallH\x00R\x12\x66orceFinalToolCall\x88\x01\x01\x12\x38\n\x06status\x18\x07 \x01(\x0e\x32 .agent_platform.common.v1.StatusR\x06status\x12\x1f\n\x0b\x64\x61taset_ids\x18\x08 \x03(\tR\ndatasetIds\x12\x42\n\x07metrics\x18\t \x01(\x0b\x32(.agent_platform.agent.v1.AgentRunMetricsR\x07metrics\x12(\n\rerror_message\x18\n \x01(\tH\x01R\x0c\x65rrorMessage\x88\x01\x01\x42\x18\n\x16_force_final_tool_callB\x10\n\x0e_error_message"\xf0\x01\n\x0f\x41gentRunMetrics\x12!\n\x0ctotal_tokens\x18\x01 \x01(\x05R\x0btotalTokens\x12#\n\rprompt_tokens\x18\x02 \x01(\x05R\x0cpromptTokens\x12+\n\x11\x63ompletion_tokens\x18\x03 \x01(\x05R\x10\x63ompletionTokens\x12@\n\x0etotal_duration\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationR\rtotalDuration\x12&\n\x0ftool_call_count\x18\x05 \x01(\x05R\rtoolCallCountB\xe7\x01\n\x1b\x63om.agent_platform.agent.v1B\rAgentRunProtoP\x01Z?github.com/agentplatform/gen/go/agent_platform/agent/v1;agentv1\xa2\x02\x03\x41\x41X\xaa\x02\x16\x41gentPlatform.Agent.V1\xca\x02\x16\x41gentPlatform\\Agent\\V1\xe2\x02"AgentPlatform\\Agent\\V1\\GPBMetadata\xea\x02\x18\x41gentPlatform::Agent::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "agent_platform.agent.v1.agent_run_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b'\n\033com.agent_platform.agent.v1B\rAgentRunProtoP\001Z?github.com/agentplatform/gen/go/agent_platform/agent/v1;agentv1\242\002\003AAX\252\002\026AgentPlatform.Agent.V1\312\002\026AgentPlatform\\Agent\\V1\342\002"AgentPlatform\\Agent\\V1\\GPBMetadata\352\002\030AgentPlatform::Agent::V1'
    _globals["_AGENTRUN"]._serialized_start = 249
    _globals["_AGENTRUN"]._serialized_end = 823
    _globals["_AGENTRUNMETRICS"]._serialized_start = 826
    _globals["_AGENTRUNMETRICS"]._serialized_end = 1066
# @@protoc_insertion_point(module_scope)
