# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_platform/agent/v1/block.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "agent_platform/agent/v1/block.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#agent_platform/agent/v1/block.proto\x12\x17\x61gent_platform.agent.v1\x1a&agent_platform/tool/v1/tool_call.proto"\xef\x02\n\x05\x42lock\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n\x08sequence\x18\x02 \x01(\x05R\x08sequence\x12\x43\n\nuser_input\x18\x03 \x01(\x0b\x32".agent_platform.agent.v1.UserInputH\x00R\tuserInput\x12?\n\ttool_call\x18\x04 \x01(\x0b\x32 .agent_platform.tool.v1.ToolCallH\x00R\x08toolCall\x12X\n\x11\x61ssistant_message\x18\x05 \x01(\x0b\x32).agent_platform.agent.v1.AssistantMessageH\x00R\x10\x61ssistantMessage\x12O\n\x0ethinking_block\x18\x06 \x01(\x0b\x32&.agent_platform.agent.v1.ThinkingBlockH\x00R\rthinkingBlockB\t\n\x07\x63ontent"f\n\tUserInput\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x45\n\x0b\x61ttachments\x18\x02 \x03(\x0b\x32#.agent_platform.agent.v1.AttachmentR\x0b\x61ttachments"&\n\x10\x41ssistantMessage\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text"I\n\rThinkingBlock\x12\x1a\n\x08thinking\x18\x01 \x01(\tR\x08thinking\x12\x1c\n\tsignature\x18\x02 \x01(\tR\tsignature"g\n\nAttachment\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n\x08\x66ilename\x18\x02 \x01(\tR\x08\x66ilename\x12\x1b\n\tmime_type\x18\x03 \x01(\tR\x08mimeType\x12\x10\n\x03url\x18\x04 \x01(\tR\x03urlB\xe4\x01\n\x1b\x63om.agent_platform.agent.v1B\nBlockProtoP\x01Z?github.com/agentplatform/gen/go/agent_platform/agent/v1;agentv1\xa2\x02\x03\x41\x41X\xaa\x02\x16\x41gentPlatform.Agent.V1\xca\x02\x16\x41gentPlatform\\Agent\\V1\xe2\x02"AgentPlatform\\Agent\\V1\\GPBMetadata\xea\x02\x18\x41gentPlatform::Agent::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_platform.agent.v1.block_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b'\n\033com.agent_platform.agent.v1B\nBlockProtoP\001Z?github.com/agentplatform/gen/go/agent_platform/agent/v1;agentv1\242\002\003AAX\252\002\026AgentPlatform.Agent.V1\312\002\026AgentPlatform\\Agent\\V1\342\002"AgentPlatform\\Agent\\V1\\GPBMetadata\352\002\030AgentPlatform::Agent::V1'
    _globals["_BLOCK"]._serialized_start = 105
    _globals["_BLOCK"]._serialized_end = 472
    _globals["_USERINPUT"]._serialized_start = 474
    _globals["_USERINPUT"]._serialized_end = 576
    _globals["_ASSISTANTMESSAGE"]._serialized_start = 578
    _globals["_ASSISTANTMESSAGE"]._serialized_end = 616
    _globals["_THINKINGBLOCK"]._serialized_start = 618
    _globals["_THINKINGBLOCK"]._serialized_end = 691
    _globals["_ATTACHMENT"]._serialized_start = 693
    _globals["_ATTACHMENT"]._serialized_end = 796
# @@protoc_insertion_point(module_scope)
