"""Initial migration with all tables

Revision ID: 8dfcb15613a6
Revises: 
Create Date: 2025-12-04 15:30:08.298558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dfcb15613a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('tool_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('policy_agent_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('prompt_dataset_id', sa.String(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('final_reward', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('policy_tool', sa.JSON(), nullable=True),
    sa.Column('data_source_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('external_source_config', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('update_schedule', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent', sa.JSON(), nullable=False),
    sa.Column('force_final_tool_call', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('policy_agent_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajectories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_run', sa.JSON(), nullable=False),
    sa.Column('reward', sa.JSON(), nullable=True),
    sa.Column('annotation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('force_final_tool_call', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('dataset_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('benchmark_run_id', sa.String(), nullable=False),
    sa.Column('runs_per_prompt', sa.Integer(), nullable=False),
    sa.Column('max_parallel_runs', sa.Integer(), nullable=False),
    sa.Column('save_trajectories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_run_id')
    )
    op.create_table('benchmark_run_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('benchmark_run_id', sa.String(), nullable=False),
    sa.Column('prompt_dataset_row_id', sa.String(), nullable=False),
    sa.Column('reward', sa.JSON(), nullable=True),
    sa.Column('agent_run_ids', sa.JSON(), nullable=False),
    sa.Column('sme_comments', sa.JSON(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_agent_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_content', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['policy_agent_id'], ['policy_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_agent_id', sa.String(), nullable=False),
    sa.Column('tool', sa.JSON(), nullable=False),
    sa.Column('policy_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['policy_agent_id'], ['policy_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_dataset_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_dataset_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('reward_agent_id', sa.String(), nullable=False),
    sa.Column('ground_truths', sa.JSON(), nullable=False),
    sa.Column('sme_comments', sa.JSON(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_dataset_id'], ['prompt_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_breakdowns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reward_result_id', sa.String(), nullable=False),
    sa.Column('policy_agent_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reward_result_id'], ['reward_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajectory_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trajectory_id', sa.String(), nullable=False),
    sa.Column('annotator_id', sa.String(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('step_annotations', sa.JSON(), nullable=False),
    sa.Column('annotated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_truths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_dataset_row_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_dataset_row_id'], ['prompt_dataset_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sme_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_dataset_row_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_dataset_row_id'], ['prompt_dataset_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trajectory_annotation_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trajectory_annotation_id'], ['trajectory_annotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_annotations')
    op.drop_table('sme_comments')
    op.drop_table('ground_truths')
    op.drop_table('trajectory_annotations')
    op.drop_table('reward_breakdowns')
    op.drop_table('prompt_dataset_rows')
    op.drop_table('policy_tools')
    op.drop_table('policy_runs')
    op.drop_table('benchmark_run_rows')
    op.drop_table('benchmark_configs')
    op.drop_table('agent_runs')
    op.drop_table('trajectories')
    op.drop_table('tools')
    op.drop_table('reward_results')
    op.drop_table('reward_agents')
    op.drop_table('prompt_datasets')
    op.drop_table('policy_agents')
    op.drop_table('datasets')
    op.drop_table('benchmark_runs')
    op.drop_table('agents')
    # ### end Alembic commands ###

