# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_platform/tool/v1/tool_call.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "agent_platform/tool/v1/tool_call.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n&agent_platform/tool/v1/tool_call.proto\x12\x16\x61gent_platform.tool.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto"\x85\x02\n\x08ToolCall\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n\x07tool_id\x18\x02 \x01(\tR\x06toolId\x12-\n\x05input\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructR\x05input\x12/\n\x06output\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructR\x06output\x12\x39\n\nstarted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\x12\x35\n\x08\x64uration\x18\x06 \x01(\x0b\x32\x19.google.protobuf.DurationR\x08\x64uration"x\n\x12\x46orceFinalToolCall\x12\x17\n\x07tool_id\x18\x01 \x01(\tR\x06toolId\x12I\n\x14\x66orced_output_schema\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructR\x12\x66orcedOutputSchemaB\xe0\x01\n\x1a\x63om.agent_platform.tool.v1B\rToolCallProtoP\x01Z=github.com/agentplatform/gen/go/agent_platform/tool/v1;toolv1\xa2\x02\x03\x41TX\xaa\x02\x15\x41gentPlatform.Tool.V1\xca\x02\x15\x41gentPlatform\\Tool\\V1\xe2\x02!AgentPlatform\\Tool\\V1\\GPBMetadata\xea\x02\x17\x41gentPlatform::Tool::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "agent_platform.tool.v1.tool_call_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\032com.agent_platform.tool.v1B\rToolCallProtoP\001Z=github.com/agentplatform/gen/go/agent_platform/tool/v1;toolv1\242\002\003ATX\252\002\025AgentPlatform.Tool.V1\312\002\025AgentPlatform\\Tool\\V1\342\002!AgentPlatform\\Tool\\V1\\GPBMetadata\352\002\027AgentPlatform::Tool::V1"
    _globals["_TOOLCALL"]._serialized_start = 162
    _globals["_TOOLCALL"]._serialized_end = 423
    _globals["_FORCEFINALTOOLCALL"]._serialized_start = 425
    _globals["_FORCEFINALTOOLCALL"]._serialized_end = 545
# @@protoc_insertion_point(module_scope)
