# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_platform/tool/v1/tool.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "agent_platform/tool/v1/tool.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!agent_platform/tool/v1/tool.proto\x12\x16\x61gent_platform.tool.v1\x1a\x1cgoogle/protobuf/struct.proto"\xbe\x01\n\x04Tool\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12:\n\x0cinput_schema\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructR\x0binputSchema\x12<\n\routput_schema\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructR\x0coutputSchema\x12\x18\n\x07\x63ontext\x18\x05 \x01(\tR\x07\x63ontext"B\n\x0cToolRegistry\x12\x32\n\x05tools\x18\x01 \x03(\x0b\x32\x1c.agent_platform.tool.v1.ToolR\x05toolsB\xdc\x01\n\x1a\x63om.agent_platform.tool.v1B\tToolProtoP\x01Z=github.com/agentplatform/gen/go/agent_platform/tool/v1;toolv1\xa2\x02\x03\x41TX\xaa\x02\x15\x41gentPlatform.Tool.V1\xca\x02\x15\x41gentPlatform\\Tool\\V1\xe2\x02!AgentPlatform\\Tool\\V1\\GPBMetadata\xea\x02\x17\x41gentPlatform::Tool::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_platform.tool.v1.tool_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\032com.agent_platform.tool.v1B\tToolProtoP\001Z=github.com/agentplatform/gen/go/agent_platform/tool/v1;toolv1\242\002\003ATX\252\002\025AgentPlatform.Tool.V1\312\002\025AgentPlatform\\Tool\\V1\342\002!AgentPlatform\\Tool\\V1\\GPBMetadata\352\002\027AgentPlatform::Tool::V1"
    _globals["_TOOL"]._serialized_start = 92
    _globals["_TOOL"]._serialized_end = 282
    _globals["_TOOLREGISTRY"]._serialized_start = 284
    _globals["_TOOLREGISTRY"]._serialized_end = 350
# @@protoc_insertion_point(module_scope)
